/***********************************************************************/
/******************* This file is generated by *************************/
/******************* the Compose Generator *****************************/
/***********************************************************************/

#include "Compose.gen.h"

//generated compose tree
const Node Compose::root[] PROGMEM = {
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) NODE_140707421760944}},
	{{0, 0, L2, KEY_TILDE}, {(uint16_t) NODE_140707421761024}},
	{{0, 0, L6, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421760864}},
	{{0, 0, L1, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421761264}},
	{{0, 0, L1, KEY_EQUAL}, {(uint16_t) NODE_140707421876368}},
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) NODE_140707421876608}},
	{{0, 0, L3, KEY_TILDE}, {(uint16_t) NODE_140707421876848}},
	{{0, 0, L4, KEY_TILDE}, {(uint16_t) NODE_140707421876768}},
	{{0, 0, L3, KEY_EQUAL}, {(uint16_t) NODE_140707421877088}},
	{{0, 0, L2, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421877248}},
	{{0, 0, L6, KEY_EQUAL}, {(uint16_t) NODE_140707421877408}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_140707421877808}},
	{{0, 0, L3, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421877968}},
	{{0, 0, L4, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421878288}},
	{{0, 0, L5, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421878208}},
	{{0, 0, L5, KEY_EQUAL}, {(uint16_t) NODE_140707421878128}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_140707421878608}},
	{{0, 0, L6, KEY_TILDE}, {(uint16_t) NODE_140707421878768}},
	{{1, 0, L3, KEY_TAB}, {(uint16_t) NODE_140707421879248}},
};

const Node Compose::NODE_140707421760944[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2c6}},
	{{0, 1, L1, KEY_TILDE}, {0x302}},
	{{0, 1, L1, KEY_SPACE}, {0x5e}},
	{{0, 1, L2, KEY_D}, {0xc2}},
	{{0, 1, L2, KEY_F}, {0xca}},
	{{0, 1, L2, KEY_S}, {0xce}},
	{{0, 1, L2, KEY_G}, {0xd4}},
	{{0, 1, L2, KEY_A}, {0xdb}},
	{{0, 1, L1, KEY_D}, {0xe2}},
	{{0, 1, L1, KEY_F}, {0xea}},
	{{0, 1, L1, KEY_S}, {0xee}},
	{{0, 1, L1, KEY_G}, {0xf4}},
	{{0, 1, L1, KEY_A}, {0xfb}},
	{{0, 1, L2, KEY_R}, {0x108}},
	{{0, 1, L1, KEY_R}, {0x109}},
	{{0, 1, L2, KEY_I}, {0x11c}},
	{{0, 1, L1, KEY_I}, {0x11d}},
	{{0, 1, L2, KEY_U}, {0x124}},
	{{0, 1, L1, KEY_U}, {0x125}},
	{{0, 1, L2, KEY_SLASH}, {0x134}},
	{{0, 1, L1, KEY_SLASH}, {0x135}},
	{{0, 1, L2, KEY_H}, {0x15c}},
	{{0, 1, L1, KEY_H}, {0x15d}},
	{{0, 1, L2, KEY_T}, {0x174}},
	{{0, 1, L1, KEY_T}, {0x175}},
	{{0, 1, L2, KEY_QUOTE}, {0x176}},
	{{0, 1, L1, KEY_QUOTE}, {0x177}},
	{{0, 1, L2, KEY_B}, {0x1e90}},
	{{0, 1, L1, KEY_B}, {0x1e91}},
	{{1, 0, L6, KEY_TILDE}, {(uint16_t) NODE_140707421636224}},
};

const Node Compose::NODE_140707421636224[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1eac}},
	{{0, 1, L1, KEY_D}, {0x1ead}},
	{{0, 1, L2, KEY_F}, {0x1ec6}},
	{{0, 1, L1, KEY_F}, {0x1ec7}},
	{{0, 1, L2, KEY_G}, {0x1ed8}},
	{{1, 1, L1, KEY_G}, {0x1ed9}},
};

const Node Compose::NODE_140707421761024[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2c7}},
	{{0, 1, L2, KEY_TILDE}, {0x30c}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_140707421872192}},
	{{0, 1, L1, KEY_0}, {0x2080}},
	{{0, 1, L1, KEY_1}, {0x2081}},
	{{0, 1, L1, KEY_2}, {0x2082}},
	{{0, 1, L1, KEY_3}, {0x2083}},
	{{0, 1, L1, KEY_4}, {0x2084}},
	{{0, 1, L1, KEY_5}, {0x2085}},
	{{0, 1, L1, KEY_6}, {0x2086}},
	{{0, 1, L1, KEY_7}, {0x2087}},
	{{0, 1, L1, KEY_8}, {0x2088}},
	{{0, 1, L1, KEY_9}, {0x2089}},
	{{0, 1, L1, KEY_SPACE}, {0x2c7}},
	{{0, 1, L2, KEY_R}, {0x10c}},
	{{0, 1, L1, KEY_R}, {0x10d}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x10e}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x10f}},
	{{0, 1, L2, KEY_F}, {0x11a}},
	{{0, 1, L1, KEY_F}, {0x11b}},
	{{0, 1, L2, KEY_E}, {0x13d}},
	{{0, 1, L1, KEY_E}, {0x13e}},
	{{0, 1, L2, KEY_J}, {0x147}},
	{{0, 1, L1, KEY_J}, {0x148}},
	{{0, 1, L2, KEY_K}, {0x158}},
	{{0, 1, L1, KEY_K}, {0x159}},
	{{0, 1, L2, KEY_H}, {0x160}},
	{{0, 1, L1, KEY_H}, {0x161}},
	{{0, 1, L2, KEY_L}, {0x164}},
	{{0, 1, L1, KEY_L}, {0x165}},
	{{0, 1, L2, KEY_B}, {0x17d}},
	{{0, 1, L1, KEY_B}, {0x17e}},
	{{0, 1, L2, KEY_D}, {0x1cd}},
	{{0, 1, L1, KEY_D}, {0x1ce}},
	{{0, 1, L2, KEY_S}, {0x1cf}},
	{{0, 1, L1, KEY_S}, {0x1d0}},
	{{0, 1, L2, KEY_G}, {0x1d1}},
	{{0, 1, L1, KEY_G}, {0x1d2}},
	{{0, 1, L2, KEY_A}, {0x1d3}},
	{{0, 1, L1, KEY_A}, {0x1d4}},
	{{0, 1, L2, KEY_Z}, {0x1d9}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_140707421555344}},
	{{0, 1, L1, KEY_Z}, {0x1da}},
	{{0, 1, L2, KEY_I}, {0x1e6}},
	{{0, 1, L1, KEY_I}, {0x1e7}},
	{{0, 1, L2, KEY_Y}, {0x1e8}},
	{{0, 1, L1, KEY_Y}, {0x1e9}},
	{{0, 1, L1, KEY_SLASH}, {0x1f0}},
	{{0, 1, L2, KEY_U}, {0x21e}},
	{{1, 1, L1, KEY_U}, {0x21f}},
};

const Node Compose::NODE_140707421872192[] PROGMEM = {
	{{0, 0, L2, KEY_SEMICOLON}, {(uint16_t) NODE_140707421872432}},
	{{1, 0, L1, KEY_SEMICOLON}, {(uint16_t) NODE_140707421872592}},
};

const Node Compose::NODE_140707421872432[] PROGMEM = {
	{{0, 1, L2, KEY_B}, {0x1c4}},
	{{1, 1, L1, KEY_B}, {0x1c5}},
};

const Node Compose::NODE_140707421872592[] PROGMEM = {
	{{1, 1, L1, KEY_B}, {0x1c6}},
};

const Node Compose::NODE_140707421555344[] PROGMEM = {
	{{0, 1, L2, KEY_A}, {0x1d9}},
	{{1, 1, L1, KEY_A}, {0x1da}},
};

const Node Compose::NODE_140707421760864[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2d8}},
	{{0, 1, L6, KEY_RIGHT_BRACE}, {0x306}},
	{{0, 1, L2, KEY_U}, {0x1e2a}},
	{{0, 1, L1, KEY_U}, {0x1e2b}},
	{{0, 1, L5, KEY_5}, {0x263f}},
	{{0, 1, L1, KEY_SPACE}, {0x2d8}},
	{{0, 1, L2, KEY_D}, {0x102}},
	{{0, 1, L1, KEY_D}, {0x103}},
	{{0, 1, L2, KEY_F}, {0x114}},
	{{0, 1, L1, KEY_F}, {0x115}},
	{{0, 1, L2, KEY_I}, {0x11e}},
	{{0, 1, L1, KEY_I}, {0x11f}},
	{{0, 1, L2, KEY_S}, {0x12c}},
	{{0, 1, L1, KEY_S}, {0x12d}},
	{{0, 1, L2, KEY_G}, {0x14e}},
	{{0, 1, L1, KEY_G}, {0x14f}},
	{{0, 1, L2, KEY_A}, {0x16c}},
	{{0, 1, L1, KEY_A}, {0x16d}},
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) NODE_140707421593904}},
	{{1, 0, L6, KEY_TILDE}, {(uint16_t) NODE_140707421637584}},
};

const Node Compose::NODE_140707421593904[] PROGMEM = {
	{{0, 1, L2, KEY_F}, {0x1e1c}},
	{{1, 1, L1, KEY_F}, {0x1e1d}},
};

const Node Compose::NODE_140707421637584[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1eb6}},
	{{1, 1, L1, KEY_D}, {0x1eb7}},
};

const Node Compose::NODE_140707421761264[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0xb4}},
	{{0, 1, L1, KEY_RIGHT_BRACE}, {0x301}},
	{{0, 0, L3, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421816448}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_140707421779984}},
	{{0, 1, L1, KEY_SPACE}, {0xb4}},
	{{0, 1, L2, KEY_D}, {0xc1}},
	{{0, 1, L2, KEY_F}, {0xc9}},
	{{0, 1, L2, KEY_S}, {0xcd}},
	{{0, 1, L2, KEY_G}, {0xd3}},
	{{0, 1, L2, KEY_A}, {0xda}},
	{{0, 1, L2, KEY_QUOTE}, {0xdd}},
	{{0, 1, L1, KEY_D}, {0xe1}},
	{{0, 1, L1, KEY_F}, {0xe9}},
	{{0, 1, L1, KEY_S}, {0xed}},
	{{0, 1, L1, KEY_G}, {0xf3}},
	{{0, 1, L1, KEY_A}, {0xfa}},
	{{0, 1, L1, KEY_QUOTE}, {0xfd}},
	{{0, 1, L2, KEY_R}, {0x106}},
	{{0, 1, L1, KEY_R}, {0x107}},
	{{0, 1, L2, KEY_E}, {0x139}},
	{{0, 1, L1, KEY_E}, {0x13a}},
	{{0, 1, L2, KEY_J}, {0x143}},
	{{0, 1, L1, KEY_J}, {0x144}},
	{{0, 1, L2, KEY_K}, {0x154}},
	{{0, 1, L1, KEY_K}, {0x155}},
	{{0, 1, L2, KEY_H}, {0x15a}},
	{{0, 1, L1, KEY_H}, {0x15b}},
	{{0, 1, L2, KEY_B}, {0x179}},
	{{0, 1, L1, KEY_B}, {0x17a}},
	{{0, 1, L2, KEY_Z}, {0x1d7}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_140707421554704}},
	{{0, 1, L1, KEY_Z}, {0x1d8}},
	{{0, 1, L2, KEY_I}, {0x1f4}},
	{{0, 1, L1, KEY_I}, {0x1f5}},
	{{0, 0, L3, KEY_EQUAL}, {(uint16_t) NODE_140707421569968}},
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) NODE_140707421572048}},
	{{0, 0, L6, KEY_EQUAL}, {(uint16_t) NODE_140707421573008}},
	{{0, 1, L2, KEY_Y}, {0x1e30}},
	{{0, 1, L1, KEY_Y}, {0x1e31}},
	{{0, 1, L2, KEY_M}, {0x1e3e}},
	{{0, 1, L1, KEY_M}, {0x1e3f}},
	{{0, 0, L2, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421596704}},
	{{0, 1, L2, KEY_V}, {0x1e54}},
	{{0, 1, L1, KEY_V}, {0x1e55}},
	{{0, 1, L2, KEY_T}, {0x1e82}},
	{{0, 1, L1, KEY_T}, {0x1e83}},
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) NODE_140707421635424}},
	{{0, 0, L6, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421636464}},
	{{1, 0, L5, KEY_TILDE}, {(uint16_t) NODE_140707421132656}},
};

const Node Compose::NODE_140707421816448[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1fe}},
	{{1, 1, L1, KEY_G}, {0x1ff}},
};

const Node Compose::NODE_140707421779984[] PROGMEM = {
	{{0, 0, L2, KEY_D}, {(uint16_t) NODE_140707421780304}},
	{{1, 0, L1, KEY_D}, {(uint16_t) NODE_140707421780144}},
};

const Node Compose::NODE_140707421780304[] PROGMEM = {
	{{1, 1, L2, KEY_F}, {0x1fc}},
};

const Node Compose::NODE_140707421780144[] PROGMEM = {
	{{1, 1, L1, KEY_F}, {0x1fd}},
};

const Node Compose::NODE_140707421554704[] PROGMEM = {
	{{0, 1, L2, KEY_A}, {0x1d7}},
	{{0, 1, L1, KEY_A}, {0x1d8}},
	{{0, 1, L2, KEY_S}, {0x1e2e}},
	{{1, 1, L1, KEY_S}, {0x1e2f}},
};

const Node Compose::NODE_140707421569968[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1fa}},
	{{1, 1, L1, KEY_D}, {0x1fb}},
};

const Node Compose::NODE_140707421572048[] PROGMEM = {
	{{0, 1, L2, KEY_R}, {0x1e08}},
	{{1, 1, L1, KEY_R}, {0x1e09}},
};

const Node Compose::NODE_140707421573008[] PROGMEM = {
	{{0, 1, L2, KEY_F}, {0x1e16}},
	{{0, 1, L1, KEY_F}, {0x1e17}},
	{{0, 1, L2, KEY_G}, {0x1e52}},
	{{1, 1, L1, KEY_G}, {0x1e53}},
};

const Node Compose::NODE_140707421596704[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1e4c}},
	{{0, 1, L1, KEY_G}, {0x1e4d}},
	{{0, 1, L2, KEY_A}, {0x1e78}},
	{{1, 1, L1, KEY_A}, {0x1e79}},
};

const Node Compose::NODE_140707421635424[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1ea4}},
	{{0, 1, L1, KEY_D}, {0x1ea5}},
	{{0, 1, L2, KEY_F}, {0x1ebe}},
	{{0, 1, L1, KEY_F}, {0x1ebf}},
	{{0, 1, L2, KEY_G}, {0x1ed0}},
	{{1, 1, L1, KEY_G}, {0x1ed1}},
};

const Node Compose::NODE_140707421636464[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1eae}},
	{{1, 1, L1, KEY_D}, {0x1eaf}},
};

const Node Compose::NODE_140707421132656[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1eda}},
	{{0, 1, L1, KEY_G}, {0x1edb}},
	{{0, 1, L2, KEY_A}, {0x1ee8}},
	{{1, 1, L1, KEY_A}, {0x1ee9}},
};

const Node Compose::NODE_140707421876368[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x60}},
	{{0, 1, L1, KEY_EQUAL}, {0x300}},
	{{0, 1, L1, KEY_SPACE}, {0x60}},
	{{0, 1, L2, KEY_D}, {0xc0}},
	{{0, 1, L2, KEY_F}, {0xc8}},
	{{0, 1, L2, KEY_S}, {0xcc}},
	{{0, 1, L2, KEY_G}, {0xd2}},
	{{0, 1, L2, KEY_A}, {0xd9}},
	{{0, 1, L1, KEY_D}, {0xe0}},
	{{0, 1, L1, KEY_F}, {0xe8}},
	{{0, 1, L1, KEY_S}, {0xec}},
	{{0, 1, L1, KEY_G}, {0xf2}},
	{{0, 1, L1, KEY_A}, {0xf9}},
	{{0, 1, L2, KEY_Z}, {0x1db}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_140707421555504}},
	{{0, 1, L1, KEY_Z}, {0x1dc}},
	{{0, 1, L2, KEY_J}, {0x1f8}},
	{{0, 1, L1, KEY_J}, {0x1f9}},
	{{0, 0, L6, KEY_EQUAL}, {(uint16_t) NODE_140707421572768}},
	{{0, 1, L2, KEY_T}, {0x1e80}},
	{{0, 1, L1, KEY_T}, {0x1e81}},
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) NODE_140707421635344}},
	{{0, 0, L6, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421636864}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_140707421132896}},
	{{0, 1, L2, KEY_QUOTE}, {0x1ef2}},
	{{1, 1, L1, KEY_QUOTE}, {0x1ef3}},
};

const Node Compose::NODE_140707421555504[] PROGMEM = {
	{{0, 1, L2, KEY_A}, {0x1db}},
	{{1, 1, L1, KEY_A}, {0x1dc}},
};

const Node Compose::NODE_140707421572768[] PROGMEM = {
	{{0, 1, L2, KEY_F}, {0x1e14}},
	{{0, 1, L1, KEY_F}, {0x1e15}},
	{{0, 1, L2, KEY_G}, {0x1e50}},
	{{1, 1, L1, KEY_G}, {0x1e51}},
};

const Node Compose::NODE_140707421635344[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1ea6}},
	{{0, 1, L1, KEY_D}, {0x1ea7}},
	{{0, 1, L2, KEY_F}, {0x1ec0}},
	{{0, 1, L1, KEY_F}, {0x1ec1}},
	{{0, 1, L2, KEY_G}, {0x1ed2}},
	{{1, 1, L1, KEY_G}, {0x1ed3}},
};

const Node Compose::NODE_140707421636864[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1eb0}},
	{{1, 1, L1, KEY_D}, {0x1eb1}},
};

const Node Compose::NODE_140707421132896[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1edc}},
	{{0, 1, L1, KEY_G}, {0x1edd}},
	{{0, 1, L2, KEY_A}, {0x1eea}},
	{{1, 1, L1, KEY_A}, {0x1eeb}},
};

const Node Compose::NODE_140707421876608[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0xb8}},
	{{0, 1, L2, KEY_EQUAL}, {0x327}},
	{{0, 1, L2, KEY_D}, {0x104}},
	{{0, 1, L1, KEY_D}, {0x105}},
	{{0, 1, L2, KEY_F}, {0x118}},
	{{0, 1, L1, KEY_F}, {0x119}},
	{{0, 1, L2, KEY_S}, {0x12e}},
	{{0, 1, L1, KEY_S}, {0x12f}},
	{{0, 1, L2, KEY_A}, {0x172}},
	{{0, 1, L1, KEY_A}, {0x173}},
	{{0, 1, L2, KEY_G}, {0x1ea}},
	{{0, 1, L1, KEY_G}, {0x1eb}},
	{{0, 1, L1, KEY_SPACE}, {0xb8}},
	{{0, 1, L2, KEY_R}, {0xc7}},
	{{0, 1, L1, KEY_R}, {0xe7}},
	{{0, 1, L2, KEY_I}, {0x122}},
	{{0, 1, L1, KEY_I}, {0x123}},
	{{0, 1, L2, KEY_Y}, {0x136}},
	{{0, 1, L1, KEY_Y}, {0x137}},
	{{0, 1, L2, KEY_E}, {0x13b}},
	{{0, 1, L1, KEY_E}, {0x13c}},
	{{0, 1, L2, KEY_J}, {0x145}},
	{{0, 1, L1, KEY_J}, {0x146}},
	{{0, 1, L2, KEY_K}, {0x156}},
	{{0, 1, L1, KEY_K}, {0x157}},
	{{0, 1, L2, KEY_H}, {0x15e}},
	{{0, 1, L1, KEY_H}, {0x15f}},
	{{0, 1, L2, KEY_L}, {0x162}},
	{{0, 1, L1, KEY_L}, {0x163}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x1e10}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x1e11}},
	{{0, 1, L2, KEY_U}, {0x1e28}},
	{{1, 1, L1, KEY_U}, {0x1e29}},
};

const Node Compose::NODE_140707421876848[] PROGMEM = {
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) NODE_140707421876928}},
	{{0, 0, L4, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421878528}},
	{{0, 1, L5, KEY_SPACE}, {0x21bb}},
	{{0, 0, L6, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421879888}},
	{{0, 1, L1, KEY_SPACE}, {0x21bb}},
	{{0, 1, L3, KEY_SEMICOLON}, {0x2025}},
	{{0, 1, L3, KEY_Q}, {0x22ee}},
	{{0, 1, L5, KEY_5}, {0x2641}},
	{{0, 1, L3, KEY_R}, {0x2423}},
	{{0, 1, L3, KEYPAD_3}, {0x21cb}},
	{{0, 1, L1, KEY_D}, {0x250}},
	{{0, 1, L2, KEY_R}, {0x186}},
	{{0, 1, L1, KEY_R}, {0x254}},
	{{0, 1, L1, KEY_F}, {0x258}},
	{{0, 1, L1, KEY_U}, {0x265}},
	{{0, 1, L1, KEY_M}, {0x26f}},
	{{0, 1, L2, KEY_K}, {0x281}},
	{{0, 1, L1, KEY_K}, {0x279}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_140707421465072}},
	{{0, 1, L2, KEY_H}, {0x1a7}},
	{{0, 1, L2, KEY_W}, {0x245}},
	{{0, 1, L1, KEY_W}, {0x28c}},
	{{0, 1, L1, KEY_T}, {0x28d}},
	{{0, 1, L1, KEY_QUOTE}, {0x28e}},
	{{0, 1, L5, KEY_E}, {0x28e}},
	{{0, 1, L1, KEY_3}, {0x190}},
	{{0, 1, L5, KEY_D}, {0x252}},
	{{1, 1, L6, KEY_T}, {0x1b1}},
};

const Node Compose::NODE_140707421876928[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2db}},
	{{0, 1, L2, KEY_EQUAL}, {0x328}},
	{{0, 1, L1, KEY_SPACE}, {0x2db}},
	{{0, 1, L2, KEY_F}, {0x228}},
	{{1, 1, L1, KEY_F}, {0x229}},
};

const Node Compose::NODE_140707421878528[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2f5}},
	{{0, 1, L4, KEY_RIGHT_BRACE}, {0x30f}},
	{{0, 1, L2, KEY_D}, {0x200}},
	{{0, 1, L1, KEY_D}, {0x201}},
	{{0, 1, L2, KEY_F}, {0x204}},
	{{0, 1, L1, KEY_F}, {0x205}},
	{{0, 1, L2, KEY_S}, {0x208}},
	{{0, 1, L1, KEY_S}, {0x209}},
	{{0, 1, L2, KEY_G}, {0x20c}},
	{{0, 1, L1, KEY_G}, {0x20d}},
	{{0, 1, L2, KEY_K}, {0x210}},
	{{0, 1, L1, KEY_K}, {0x211}},
	{{0, 1, L2, KEY_A}, {0x214}},
	{{1, 1, L1, KEY_A}, {0x215}},
};

const Node Compose::NODE_140707421879888[] PROGMEM = {
	{{0, 1, L6, KEY_RIGHT_BRACE}, {0x311}},
	{{0, 1, L2, KEY_D}, {0x202}},
	{{0, 1, L1, KEY_D}, {0x203}},
	{{0, 1, L2, KEY_F}, {0x206}},
	{{0, 1, L1, KEY_F}, {0x207}},
	{{0, 1, L2, KEY_S}, {0x20a}},
	{{0, 1, L1, KEY_S}, {0x20b}},
	{{0, 1, L2, KEY_G}, {0x20e}},
	{{0, 1, L1, KEY_G}, {0x20f}},
	{{0, 1, L2, KEY_K}, {0x212}},
	{{0, 1, L1, KEY_K}, {0x213}},
	{{0, 1, L2, KEY_A}, {0x216}},
	{{1, 1, L1, KEY_A}, {0x217}},
};

const Node Compose::NODE_140707421465072[] PROGMEM = {
	{{0, 0, L1, KEY_K}, {(uint16_t) NODE_140707421464992}},
	{{0, 0, L1, KEY_D}, {(uint16_t) NODE_140707421465952}},
	{{0, 0, L5, KEY_D}, {(uint16_t) NODE_140707421465872}},
	{{1, 0, L1, KEY_U}, {(uint16_t) NODE_140707421466192}},
};

const Node Compose::NODE_140707421464992[] PROGMEM = {
	{{1, 1, L1, KEY_K}, {0x27a}},
};

const Node Compose::NODE_140707421465952[] PROGMEM = {
	{{1, 1, L1, KEY_D}, {0x252}},
};

const Node Compose::NODE_140707421465872[] PROGMEM = {
	{{1, 1, L5, KEY_D}, {0x252}},
};

const Node Compose::NODE_140707421466192[] PROGMEM = {
	{{1, 1, L1, KEY_J}, {0x270}},
};

const Node Compose::NODE_140707421876768[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2d9}},
	{{0, 1, L4, KEY_TILDE}, {0x307}},
	{{0, 1, L2, KEY_E}, {0x13f}},
	{{0, 1, L1, KEY_E}, {0x140}},
	{{0, 1, L1, KEY_SLASH}, {0x237}},
	{{0, 1, L1, KEY_SPACE}, {0x2d9}},
	{{0, 1, L2, KEY_R}, {0x10a}},
	{{0, 1, L1, KEY_R}, {0x10b}},
	{{0, 1, L2, KEY_F}, {0x116}},
	{{0, 1, L1, KEY_F}, {0x117}},
	{{0, 1, L2, KEY_I}, {0x120}},
	{{0, 1, L1, KEY_I}, {0x121}},
	{{0, 1, L2, KEY_S}, {0x130}},
	{{0, 1, L1, KEY_S}, {0x131}},
	{{0, 1, L2, KEY_B}, {0x17b}},
	{{0, 1, L1, KEY_B}, {0x17c}},
	{{0, 1, L2, KEY_D}, {0x226}},
	{{0, 1, L1, KEY_D}, {0x227}},
	{{0, 1, L2, KEY_G}, {0x22e}},
	{{0, 1, L1, KEY_G}, {0x22f}},
	{{0, 1, L2, KEY_N}, {0x1e02}},
	{{0, 1, L1, KEY_N}, {0x1e03}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x1e0a}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x1e0b}},
	{{0, 1, L2, KEY_O}, {0x1e1e}},
	{{0, 1, L1, KEY_O}, {0x1e1f}},
	{{0, 1, L2, KEY_U}, {0x1e22}},
	{{0, 1, L1, KEY_U}, {0x1e23}},
	{{0, 1, L2, KEY_M}, {0x1e40}},
	{{0, 1, L1, KEY_M}, {0x1e41}},
	{{0, 1, L2, KEY_J}, {0x1e44}},
	{{0, 1, L1, KEY_J}, {0x1e45}},
	{{0, 1, L2, KEY_V}, {0x1e56}},
	{{0, 1, L1, KEY_V}, {0x1e57}},
	{{0, 1, L2, KEY_K}, {0x1e58}},
	{{0, 1, L1, KEY_K}, {0x1e59}},
	{{0, 1, L2, KEY_H}, {0x1e60}},
	{{0, 1, L1, KEY_H}, {0x1e61}},
	{{0, 0, L1, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421615104}},
	{{0, 0, L2, KEY_TILDE}, {(uint16_t) NODE_140707421615424}},
	{{0, 1, L2, KEY_L}, {0x1e6a}},
	{{0, 1, L1, KEY_L}, {0x1e6b}},
	{{0, 1, L2, KEY_T}, {0x1e86}},
	{{0, 1, L1, KEY_T}, {0x1e87}},
	{{0, 1, L2, KEY_Q}, {0x1e8a}},
	{{0, 1, L1, KEY_Q}, {0x1e8b}},
	{{0, 1, L2, KEY_QUOTE}, {0x1e8e}},
	{{0, 1, L1, KEY_QUOTE}, {0x1e8f}},
	{{1, 1, L3, KEY_LEFT_BRACE}, {0x1e9b}},
};

const Node Compose::NODE_140707421615104[] PROGMEM = {
	{{0, 1, L2, KEY_H}, {0x1e64}},
	{{1, 1, L1, KEY_H}, {0x1e65}},
};

const Node Compose::NODE_140707421615424[] PROGMEM = {
	{{0, 1, L2, KEY_H}, {0x1e66}},
	{{1, 1, L1, KEY_H}, {0x1e67}},
};

const Node Compose::NODE_140707421877088[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2da}},
	{{0, 1, L3, KEY_EQUAL}, {0x30a}},
	{{0, 1, L1, KEY_SPACE}, {0xb0}},
	{{0, 1, L2, KEY_D}, {0xc5}},
	{{0, 1, L1, KEY_D}, {0xe5}},
	{{0, 1, L2, KEY_A}, {0x16e}},
	{{0, 1, L1, KEY_A}, {0x16f}},
	{{0, 1, L1, KEY_T}, {0x1e98}},
	{{1, 1, L1, KEY_QUOTE}, {0x1e99}},
};

const Node Compose::NODE_140707421877248[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2dc}},
	{{0, 1, L2, KEY_RIGHT_BRACE}, {0x303}},
	{{0, 1, L2, KEY_E}, {0x2c62}},
	{{0, 1, L1, KEY_E}, {0x26b}},
	{{0, 1, L1, KEY_SPACE}, {0x7e}},
	{{0, 1, L2, KEY_D}, {0xc3}},
	{{0, 1, L2, KEY_J}, {0xd1}},
	{{0, 1, L2, KEY_G}, {0xd5}},
	{{0, 1, L1, KEY_D}, {0xe3}},
	{{0, 1, L1, KEY_J}, {0xf1}},
	{{0, 1, L1, KEY_G}, {0xf5}},
	{{0, 1, L2, KEY_S}, {0x128}},
	{{0, 1, L1, KEY_S}, {0x129}},
	{{0, 1, L2, KEY_A}, {0x168}},
	{{0, 1, L1, KEY_A}, {0x169}},
	{{0, 1, L2, KEY_W}, {0x1e7c}},
	{{0, 1, L1, KEY_W}, {0x1e7d}},
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) NODE_140707421635984}},
	{{0, 0, L6, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421637344}},
	{{0, 1, L2, KEY_F}, {0x1ebc}},
	{{0, 1, L1, KEY_F}, {0x1ebd}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_140707421133456}},
	{{0, 1, L2, KEY_QUOTE}, {0x1ef8}},
	{{1, 1, L1, KEY_QUOTE}, {0x1ef9}},
};

const Node Compose::NODE_140707421635984[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1eaa}},
	{{0, 1, L1, KEY_D}, {0x1eab}},
	{{0, 1, L2, KEY_F}, {0x1ec4}},
	{{0, 1, L1, KEY_F}, {0x1ec5}},
	{{0, 1, L2, KEY_G}, {0x1ed6}},
	{{1, 1, L1, KEY_G}, {0x1ed7}},
};

const Node Compose::NODE_140707421637344[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1eb4}},
	{{1, 1, L1, KEY_D}, {0x1eb5}},
};

const Node Compose::NODE_140707421133456[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1ee0}},
	{{0, 1, L1, KEY_G}, {0x1ee1}},
	{{0, 1, L2, KEY_A}, {0x1eee}},
	{{1, 1, L1, KEY_A}, {0x1eef}},
};

const Node Compose::NODE_140707421877408[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0xaf}},
	{{0, 1, L6, KEY_EQUAL}, {0x304}},
	{{0, 0, L2, KEY_EQUAL}, {(uint16_t) NODE_140707421862704}},
	{{0, 1, L2, KEY_N}, {0x1e06}},
	{{0, 1, L1, KEY_N}, {0x1e07}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x1e0e}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x1e0f}},
	{{0, 1, L2, KEY_Y}, {0x1e34}},
	{{0, 1, L1, KEY_Y}, {0x1e35}},
	{{0, 1, L2, KEY_E}, {0x1e3a}},
	{{0, 1, L1, KEY_E}, {0x1e3b}},
	{{0, 1, L2, KEY_J}, {0x1e48}},
	{{0, 1, L1, KEY_J}, {0x1e49}},
	{{0, 1, L2, KEY_K}, {0x1e5e}},
	{{0, 1, L1, KEY_K}, {0x1e5f}},
	{{0, 1, L2, KEY_L}, {0x1e6e}},
	{{0, 1, L1, KEY_L}, {0x1e6f}},
	{{0, 1, L2, KEY_B}, {0x1e94}},
	{{0, 1, L1, KEY_B}, {0x1e95}},
	{{0, 1, L1, KEY_U}, {0x1e96}},
	{{0, 0, L3, KEY_TAB}, {(uint16_t) NODE_140707421779664}},
	{{0, 1, L1, KEY_SPACE}, {0xaf}},
	{{0, 1, L2, KEY_D}, {0x100}},
	{{0, 1, L1, KEY_D}, {0x101}},
	{{0, 1, L2, KEY_F}, {0x112}},
	{{0, 1, L1, KEY_F}, {0x113}},
	{{0, 1, L2, KEY_S}, {0x12a}},
	{{0, 1, L1, KEY_S}, {0x12b}},
	{{0, 1, L2, KEY_G}, {0x14c}},
	{{0, 1, L1, KEY_G}, {0x14d}},
	{{0, 1, L2, KEY_A}, {0x16a}},
	{{0, 1, L1, KEY_A}, {0x16b}},
	{{0, 1, L2, KEY_Z}, {0x1d5}},
	{{0, 0, L4, KEY_EQUAL}, {(uint16_t) NODE_140707421554624}},
	{{0, 1, L1, KEY_Z}, {0x1d6}},
	{{0, 1, L2, KEY_C}, {0x1de}},
	{{0, 1, L1, KEY_C}, {0x1df}},
	{{0, 0, L4, KEY_TILDE}, {(uint16_t) NODE_140707421556304}},
	{{0, 0, L2, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421571008}},
	{{0, 1, L2, KEY_QUOTE}, {0x232}},
	{{0, 1, L1, KEY_QUOTE}, {0x233}},
	{{0, 1, L2, KEY_I}, {0x1e20}},
	{{0, 1, L1, KEY_I}, {0x1e21}},
	{{1, 0, L6, KEY_TILDE}, {(uint16_t) NODE_140707421595744}},
};

const Node Compose::NODE_140707421862704[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1ec}},
	{{1, 1, L1, KEY_G}, {0x1ed}},
};

const Node Compose::NODE_140707421779664[] PROGMEM = {
	{{0, 0, L2, KEY_D}, {(uint16_t) NODE_140707421779744}},
	{{1, 0, L1, KEY_D}, {(uint16_t) NODE_140707421779824}},
};

const Node Compose::NODE_140707421779744[] PROGMEM = {
	{{1, 1, L2, KEY_F}, {0x1e2}},
};

const Node Compose::NODE_140707421779824[] PROGMEM = {
	{{1, 1, L1, KEY_F}, {0x1e3}},
};

const Node Compose::NODE_140707421554624[] PROGMEM = {
	{{0, 1, L2, KEY_A}, {0x1d5}},
	{{0, 1, L1, KEY_A}, {0x1d6}},
	{{0, 1, L2, KEY_D}, {0x1de}},
	{{0, 1, L1, KEY_D}, {0x1df}},
	{{0, 1, L2, KEY_G}, {0x22a}},
	{{1, 1, L1, KEY_G}, {0x22b}},
};

const Node Compose::NODE_140707421556304[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1e0}},
	{{0, 1, L1, KEY_D}, {0x1e1}},
	{{0, 1, L2, KEY_G}, {0x230}},
	{{1, 1, L1, KEY_G}, {0x231}},
};

const Node Compose::NODE_140707421571008[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x22c}},
	{{1, 1, L1, KEY_G}, {0x22d}},
};

const Node Compose::NODE_140707421595744[] PROGMEM = {
	{{0, 1, L2, KEY_E}, {0x1e38}},
	{{0, 1, L1, KEY_E}, {0x1e39}},
	{{0, 1, L2, KEY_K}, {0x1e5c}},
	{{1, 1, L1, KEY_K}, {0x1e5d}},
};

const Node Compose::NODE_140707421877808[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0xa8}},
	{{0, 1, L4, KEY_EQUAL}, {0x308}},
	{{0, 1, L1, KEY_SPACE}, {0xa8}},
	{{0, 1, L2, KEY_D}, {0xc4}},
	{{0, 1, L2, KEY_F}, {0xcb}},
	{{0, 1, L2, KEY_S}, {0xcf}},
	{{0, 1, L2, KEY_G}, {0xd6}},
	{{0, 1, L2, KEY_A}, {0xdc}},
	{{0, 1, L1, KEY_D}, {0xe4}},
	{{0, 1, L1, KEY_F}, {0xeb}},
	{{0, 1, L1, KEY_S}, {0xef}},
	{{0, 1, L1, KEY_G}, {0xf6}},
	{{0, 1, L1, KEY_A}, {0xfc}},
	{{0, 1, L1, KEY_QUOTE}, {0xff}},
	{{0, 1, L2, KEY_QUOTE}, {0x178}},
	{{0, 1, L2, KEY_U}, {0x1e26}},
	{{0, 1, L1, KEY_U}, {0x1e27}},
	{{0, 0, L2, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421597024}},
	{{0, 0, L6, KEY_EQUAL}, {(uint16_t) NODE_140707421616144}},
	{{0, 1, L2, KEY_T}, {0x1e84}},
	{{0, 1, L1, KEY_T}, {0x1e85}},
	{{0, 1, L2, KEY_Q}, {0x1e8c}},
	{{0, 1, L1, KEY_Q}, {0x1e8d}},
	{{1, 1, L1, KEY_L}, {0x1e97}},
};

const Node Compose::NODE_140707421597024[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1e4e}},
	{{1, 1, L1, KEY_G}, {0x1e4f}},
};

const Node Compose::NODE_140707421616144[] PROGMEM = {
	{{0, 1, L2, KEY_A}, {0x1e7a}},
	{{1, 1, L1, KEY_A}, {0x1e7b}},
};

const Node Compose::NODE_140707421877968[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2f}},
	{{0, 1, L3, KEY_RIGHT_BRACE}, {0x337}},
	{{0, 1, L1, KEY_SPACE}, {0x2010}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x110}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x111}},
	{{0, 1, L2, KEY_U}, {0x126}},
	{{0, 1, L1, KEY_U}, {0x127}},
	{{0, 1, L2, KEY_E}, {0x141}},
	{{0, 1, L1, KEY_E}, {0x142}},
	{{0, 1, L2, KEY_G}, {0xd8}},
	{{0, 1, L1, KEY_G}, {0xf8}},
	{{0, 1, L5, KEY_4}, {0x26a6}},
	{{0, 1, L5, KEY_6}, {0x26a7}},
	{{0, 1, L3, KEY_S}, {0x2718}},
	{{0, 1, L3, KEY_A}, {0x2718}},
	{{0, 1, L4, KEY_6}, {0x20a4}},
	{{0, 1, L2, KEY_L}, {0x166}},
	{{0, 1, L1, KEY_L}, {0x167}},
	{{0, 1, L1, KEY_N}, {0x180}},
	{{0, 1, L2, KEY_S}, {0x197}},
	{{0, 1, L2, KEY_B}, {0x1b5}},
	{{0, 1, L1, KEY_B}, {0x1b6}},
	{{0, 1, L2, KEY_I}, {0x1e4}},
	{{0, 1, L1, KEY_I}, {0x1e5}},
	{{0, 0, L1, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421570368}},
	{{1, 1, L1, KEY_S}, {0x268}},
};

const Node Compose::NODE_140707421570368[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1fe}},
	{{1, 1, L1, KEY_G}, {0x1ff}},
};

const Node Compose::NODE_140707421878288[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2dd}},
	{{0, 1, L4, KEY_RIGHT_BRACE}, {0x30b}},
	{{0, 1, L1, KEY_SPACE}, {0x2dd}},
	{{0, 1, L2, KEY_G}, {0x150}},
	{{0, 1, L1, KEY_G}, {0x151}},
	{{0, 1, L2, KEY_A}, {0x170}},
	{{1, 1, L1, KEY_A}, {0x171}},
};

const Node Compose::NODE_140707421878208[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x1fbf}},
	{{0, 1, L5, KEY_RIGHT_BRACE}, {0x313}},
	{{0, 1, L1, KEY_SPACE}, {0x1fbf}},
	{{0, 1, L2, KEY_D}, {0x1ea2}},
	{{0, 1, L1, KEY_D}, {0x1ea3}},
	{{0, 0, L1, KEY_TILDE}, {(uint16_t) NODE_140707421635824}},
	{{0, 0, L6, KEY_RIGHT_BRACE}, {(uint16_t) NODE_140707421637104}},
	{{0, 1, L2, KEY_F}, {0x1eba}},
	{{0, 1, L1, KEY_F}, {0x1ebb}},
	{{0, 1, L2, KEY_S}, {0x1ec8}},
	{{0, 1, L1, KEY_S}, {0x1ec9}},
	{{0, 1, L2, KEY_G}, {0x1ece}},
	{{0, 1, L1, KEY_G}, {0x1ecf}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_140707421133216}},
	{{0, 1, L2, KEY_A}, {0x1ee6}},
	{{0, 1, L1, KEY_A}, {0x1ee7}},
	{{0, 1, L2, KEY_QUOTE}, {0x1ef6}},
	{{1, 1, L1, KEY_QUOTE}, {0x1ef7}},
};

const Node Compose::NODE_140707421635824[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1ea8}},
	{{0, 1, L1, KEY_D}, {0x1ea9}},
	{{0, 1, L2, KEY_F}, {0x1ec2}},
	{{0, 1, L1, KEY_F}, {0x1ec3}},
	{{0, 1, L2, KEY_G}, {0x1ed4}},
	{{1, 1, L1, KEY_G}, {0x1ed5}},
};

const Node Compose::NODE_140707421637104[] PROGMEM = {
	{{0, 1, L2, KEY_D}, {0x1eb2}},
	{{1, 1, L1, KEY_D}, {0x1eb3}},
};

const Node Compose::NODE_140707421133216[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1ede}},
	{{0, 1, L1, KEY_G}, {0x1edf}},
	{{0, 1, L2, KEY_A}, {0x1eec}},
	{{1, 1, L1, KEY_A}, {0x1eed}},
};

const Node Compose::NODE_140707421878128[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x1ffe}},
	{{0, 1, L5, KEY_EQUAL}, {0x314}},
	{{1, 1, L1, KEY_SPACE}, {0x1ffe}},
};

const Node Compose::NODE_140707421878608[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2de}},
	{{0, 1, L5, KEY_TILDE}, {0x2de}},
	{{0, 1, L1, KEY_SPACE}, {0x2de}},
	{{0, 1, L3, KEY_S}, {0x2714}},
	{{0, 1, L3, KEY_A}, {0x2714}},
	{{0, 1, L2, KEY_G}, {0x1a0}},
	{{0, 1, L1, KEY_G}, {0x1a1}},
	{{0, 1, L2, KEY_A}, {0x1af}},
	{{1, 1, L1, KEY_A}, {0x1b0}},
};

const Node Compose::NODE_140707421878768[] PROGMEM = {
	{{0, 1, L5, KEY_SPACE}, {0x2e}},
	{{0, 1, L6, KEY_TILDE}, {0x323}},
	{{0, 1, L1, KEY_SPACE}, {0x2e}},
	{{0, 1, L2, KEY_N}, {0x1e04}},
	{{0, 1, L1, KEY_N}, {0x1e05}},
	{{0, 1, L2, KEY_SEMICOLON}, {0x1e0c}},
	{{0, 1, L1, KEY_SEMICOLON}, {0x1e0d}},
	{{0, 1, L2, KEY_U}, {0x1e24}},
	{{0, 1, L1, KEY_U}, {0x1e25}},
	{{0, 1, L2, KEY_Y}, {0x1e32}},
	{{0, 1, L1, KEY_Y}, {0x1e33}},
	{{0, 1, L2, KEY_E}, {0x1e36}},
	{{0, 1, L1, KEY_E}, {0x1e37}},
	{{0, 1, L2, KEY_M}, {0x1e42}},
	{{0, 1, L1, KEY_M}, {0x1e43}},
	{{0, 1, L2, KEY_J}, {0x1e46}},
	{{0, 1, L1, KEY_J}, {0x1e47}},
	{{0, 1, L2, KEY_K}, {0x1e5a}},
	{{0, 1, L1, KEY_K}, {0x1e5b}},
	{{0, 1, L2, KEY_H}, {0x1e62}},
	{{0, 1, L1, KEY_H}, {0x1e63}},
	{{0, 1, L2, KEY_L}, {0x1e6c}},
	{{0, 1, L1, KEY_L}, {0x1e6d}},
	{{0, 1, L2, KEY_W}, {0x1e7e}},
	{{0, 1, L1, KEY_W}, {0x1e7f}},
	{{0, 1, L2, KEY_T}, {0x1e88}},
	{{0, 1, L1, KEY_T}, {0x1e89}},
	{{0, 1, L2, KEY_B}, {0x1e92}},
	{{0, 1, L1, KEY_B}, {0x1e93}},
	{{0, 1, L2, KEY_D}, {0x1ea0}},
	{{0, 1, L1, KEY_D}, {0x1ea1}},
	{{0, 1, L2, KEY_F}, {0x1eb8}},
	{{0, 1, L1, KEY_F}, {0x1eb9}},
	{{0, 1, L2, KEY_S}, {0x1eca}},
	{{0, 1, L1, KEY_S}, {0x1ecb}},
	{{0, 1, L2, KEY_G}, {0x1ecc}},
	{{0, 1, L1, KEY_G}, {0x1ecd}},
	{{0, 0, L5, KEY_TILDE}, {(uint16_t) NODE_140707421133696}},
	{{0, 1, L2, KEY_A}, {0x1ee4}},
	{{0, 1, L1, KEY_A}, {0x1ee5}},
	{{0, 1, L2, KEY_QUOTE}, {0x1ef4}},
	{{1, 1, L1, KEY_QUOTE}, {0x1ef5}},
};

const Node Compose::NODE_140707421133696[] PROGMEM = {
	{{0, 1, L2, KEY_G}, {0x1ee2}},
	{{0, 1, L1, KEY_G}, {0x1ee3}},
	{{0, 1, L2, KEY_A}, {0x1ef0}},
	{{1, 1, L1, KEY_A}, {0x1ef1}},
};

const Node Compose::NODE_140707421879248[] PROGMEM = {
	{{0, 0, L1, KEY_G}, {(uint16_t) NODE_140707421879328}},
	{{0, 0, L3, KEY_Q}, {(uint16_t) NODE_140707421879088}},
	{{0, 0, L3, KEY_W}, {(uint16_t) NODE_140707421860544}},
	{{0, 0, L3, KEY_0}, {(uint16_t) NODE_140707421860784}},
	{{0, 0, L1, KEY_MINUS}, {(uint16_t) NODE_140707421815648}},
	{{0, 0, L2, KEY_H}, {(uint16_t) NODE_140707421817568}},
	{{0, 0, L1, KEY_H}, {(uint16_t) NODE_140707421817728}},
	{{0, 0, L2, KEY_L}, {(uint16_t) NODE_140707421817808}},
	{{0, 0, L1, KEY_L}, {(uint16_t) NODE_140707421818048}},
	{{0, 0, L2, KEY_F}, {(uint16_t) NODE_140707421778304}},
	{{0, 0, L2, KEY_E}, {(uint16_t) NODE_140707421778464}},
	{{0, 0, L1, KEY_E}, {(uint16_t) NODE_140707421778544}},
	{{0, 0, L1, KEY_S}, {(uint16_t) NODE_140707421779344}},
	{{0, 0, L2, KEY_S}, {(uint16_t) NODE_140707421779264}},
	{{0, 0, L1, KEY_B}, {(uint16_t) NODE_140707421780464}},
	{{0, 0, L1, KEY_O}, {(uint16_t) NODE_140707421780704}},
	{{0, 0, L2, KEY_O}, {(uint16_t) NODE_140707421781024}},
	{{0, 0, L3, KEY_LEFT_BRACE}, {(uint16_t) NODE_140707421781264}},
	{{0, 0, L2, KEY_SEMICOLON}, {(uint16_t) NODE_140707421781664}},
	{{0, 0, L1, KEY_SEMICOLON}, {(uint16_t) NODE_140707421781904}},
	{{0, 0, L2, KEY_J}, {(uint16_t) NODE_140707421872992}},
	{{0, 0, L1, KEY_J}, {(uint16_t) NODE_140707421873232}},
	{{0, 0, L1, KEY_2}, {(uint16_t) NODE_140707421874352}},
	{{0, 0, L3, KEY_Y}, {(uint16_t) NODE_140707421873472}},
	{{0, 0, L3, KEY_H}, {(uint16_t) NODE_140707421874592}},
	{{0, 0, L1, KEY_1}, {(uint16_t) NODE_140707421874912}},
	{{0, 0, L2, KEYPAD_9}, {(uint16_t) NODE_140707421875552}},
	{{0, 0, L5, KEY_SPACE}, {(uint16_t) NODE_140707421875952}},
	{{0, 0, L1, KEY_7}, {(uint16_t) NODE_140707421421632}},
	{{0, 0, L2, KEY_K}, {(uint16_t) NODE_140707421421872}},
	{{0, 0, L1, KEY_K}, {(uint16_t) NODE_140707421422832}},
	{{0, 0, L1, KEY_3}, {(uint16_t) NODE_140707421424272}},
	{{0, 0, L1, KEY_4}, {(uint16_t) NODE_140707421424352}},
	{{0, 0, L1, KEY_5}, {(uint16_t) NODE_140707421424672}},
	{{0, 0, L3, KEY_SEMICOLON}, {(uint16_t) NODE_140707421446368}},
	{{0, 0, L1, KEY_R}, {(uint16_t) NODE_140707421446608}},
	{{0, 0, L5, KEY_5}, {(uint16_t) NODE_140707421446688}},
	{{0, 0, L5, KEY_4}, {(uint16_t) NODE_140707421446928}},
	{{0, 1, L1, KEY_TAB}, {0x266b}},
	{{0, 1, L3, KEY_TAB}, {0x266b}},
	{{0, 0, L3, KEY_U}, {(uint16_t) NODE_140707421448048}},
	{{0, 0, L2, KEY_R}, {(uint16_t) NODE_140707421448368}},
	{{0, 0, L3, KEY_E}, {(uint16_t) NODE_140707421448208}},
	{{0, 0, L6, KEYPAD_0}, {(uint16_t) NODE_140707421448608}},
	{{0, 0, L2, KEYPAD_7}, {(uint16_t) NODE_140707421448768}},
	{{0, 0, L2, KEYPAD_8}, {(uint16_t) NODE_140707421449088}},
	{{0, 0, L6, KEY_SEMICOLON}, {(uint16_t) NODE_140707421449168}},
	{{0, 0, L2, KEYPAD_0}, {(uint16_t) NODE_140707421449568}},
	{{0, 0, L1, KEY_V}, {(uint16_t) NODE_140707421449648}},
	{{0, 0, L1, KEY_PERIOD}, {(uint16_t) NODE_140707421463072}},
	{{1, 0, L2, KEY_PERIOD}, {(uint16_t) NODE_140707421463312}},
};

const Node Compose::NODE_140707421879328[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x25cc}},
	{{1, 0, L1, KEY_V}, {(uint16_t) NODE_140707421450128}},
};

const Node Compose::NODE_140707421450128[] PROGMEM = {
	{{1, 1, L1, KEY_L}, {0x2325}},
};

const Node Compose::NODE_140707421879088[] PROGMEM = {
	{{1, 1, L1, KEY_G}, {0x25cc}},
};

const Node Compose::NODE_140707421860544[] PROGMEM = {
	{{1, 1, L3, KEY_W}, {0x332}},
};

const Node Compose::NODE_140707421860784[] PROGMEM = {
	{{1, 1, L3, KEY_0}, {0x2bc}},
};

const Node Compose::NODE_140707421815648[] PROGMEM = {
	{{0, 1, L2, KEY_U}, {0x126}},
	{{0, 1, L1, KEY_U}, {0x127}},
	{{1, 1, L4, KEY_6}, {0x20a4}},
};

const Node Compose::NODE_140707421817568[] PROGMEM = {
	{{1, 1, L1, KEY_COMMA}, {0x218}},
};

const Node Compose::NODE_140707421817728[] PROGMEM = {
	{{0, 1, L1, KEY_COMMA}, {0x219}},
	{{1, 1, L1, KEY_L}, {0xfb06}},
};

const Node Compose::NODE_140707421817808[] PROGMEM = {
	{{1, 1, L1, KEY_COMMA}, {0x21a}},
};

const Node Compose::NODE_140707421818048[] PROGMEM = {
	{{0, 1, L1, KEY_COMMA}, {0x21b}},
	{{1, 1, L1, KEY_M}, {0x2122}},
};

const Node Compose::NODE_140707421778304[] PROGMEM = {
	{{1, 1, L2, KEY_F}, {0x18f}},
};

const Node Compose::NODE_140707421778464[] PROGMEM = {
	{{0, 1, L1, KEY_PERIOD}, {0x13f}},
	{{0, 1, L2, KEY_SLASH}, {0x1c7}},
	{{1, 1, L1, KEY_SLASH}, {0x1c8}},
};

const Node Compose::NODE_140707421778544[] PROGMEM = {
	{{0, 1, L1, KEY_PERIOD}, {0x140}},
	{{1, 1, L1, KEY_SLASH}, {0x1c9}},
};

const Node Compose::NODE_140707421779344[] PROGMEM = {
	{{0, 1, L1, KEY_S}, {0x131}},
	{{1, 1, L1, KEY_SLASH}, {0x133}},
};

const Node Compose::NODE_140707421779264[] PROGMEM = {
	{{0, 1, L2, KEY_S}, {0x130}},
	{{1, 1, L2, KEY_SLASH}, {0x132}},
};

const Node Compose::NODE_140707421780464[] PROGMEM = {
	{{0, 1, L1, KEY_U}, {0x292}},
	{{1, 1, L1, KEY_B}, {0x292}},
};

const Node Compose::NODE_140707421780704[] PROGMEM = {
	{{0, 1, L1, KEY_O}, {0xfb00}},
	{{0, 1, L1, KEY_S}, {0xfb01}},
	{{1, 1, L1, KEY_E}, {0xfb02}},
};

const Node Compose::NODE_140707421781024[] PROGMEM = {
	{{0, 1, L1, KEY_S}, {0xfb03}},
	{{1, 1, L1, KEY_E}, {0xfb04}},
};

const Node Compose::NODE_140707421781264[] PROGMEM = {
	{{1, 1, L1, KEY_L}, {0xfb05}},
};

const Node Compose::NODE_140707421781664[] PROGMEM = {
	{{0, 1, L2, KEY_B}, {0x1f1}},
	{{1, 1, L1, KEY_B}, {0x1f2}},
};

const Node Compose::NODE_140707421781904[] PROGMEM = {
	{{0, 1, L1, KEY_B}, {0x1f3}},
	{{1, 0, L1, KEY_D}, {(uint16_t) NODE_140707421462672}},
};

const Node Compose::NODE_140707421462672[] PROGMEM = {
	{{1, 1, L1, KEY_I}, {0x2020}},
};

const Node Compose::NODE_140707421872992[] PROGMEM = {
	{{0, 1, L2, KEY_SLASH}, {0x1ca}},
	{{1, 1, L1, KEY_SLASH}, {0x1cb}},
};

const Node Compose::NODE_140707421873232[] PROGMEM = {
	{{1, 1, L1, KEY_SLASH}, {0x1cc}},
};

const Node Compose::NODE_140707421874352[] PROGMEM = {
	{{0, 1, L3, KEY_Y}, {0x203c}},
	{{0, 1, L3, KEY_H}, {0x2047}},
	{{0, 1, L1, KEY_3}, {0x2154}},
	{{1, 1, L1, KEY_5}, {0x2156}},
};

const Node Compose::NODE_140707421873472[] PROGMEM = {
	{{0, 1, L1, KEY_2}, {0x203c}},
	{{0, 1, L3, KEY_H}, {0x2049}},
	{{1, 1, L6, KEY_SEMICOLON}, {0x26a0}},
};

const Node Compose::NODE_140707421874592[] PROGMEM = {
	{{0, 1, L1, KEY_2}, {0x2047}},
	{{1, 1, L3, KEY_Y}, {0x2048}},
};

const Node Compose::NODE_140707421874912[] PROGMEM = {
	{{0, 0, L3, KEY_H}, {(uint16_t) NODE_140707421875072}},
	{{0, 0, L3, KEY_Y}, {(uint16_t) NODE_140707421874992}},
	{{0, 0, L4, KEY_H}, {(uint16_t) NODE_140707421875232}},
	{{0, 0, L4, KEY_Y}, {(uint16_t) NODE_140707421875392}},
	{{0, 1, L1, KEY_3}, {0x2153}},
	{{0, 1, L1, KEY_5}, {0x2155}},
	{{0, 1, L1, KEY_6}, {0x2159}},
	{{0, 1, L1, KEY_8}, {0x215b}},
	{{0, 1, L3, KEY_S}, {0x215f}},
	{{0, 1, L1, KEY_4}, {0xbc}},
	{{1, 1, L1, KEY_2}, {0xbd}},
};

const Node Compose::NODE_140707421875072[] PROGMEM = {
	{{1, 1, L3, KEY_Y}, {0x203d}},
};

const Node Compose::NODE_140707421874992[] PROGMEM = {
	{{1, 1, L3, KEY_H}, {0x203d}},
};

const Node Compose::NODE_140707421875232[] PROGMEM = {
	{{1, 1, L4, KEY_Y}, {0x2e18}},
};

const Node Compose::NODE_140707421875392[] PROGMEM = {
	{{1, 1, L4, KEY_H}, {0x2e18}},
};

const Node Compose::NODE_140707421875552[] PROGMEM = {
	{{1, 1, L2, KEYPAD_9}, {0x2021}},
};

const Node Compose::NODE_140707421875952[] PROGMEM = {
	{{1, 1, L5, KEY_SPACE}, {0x2d}},
};

const Node Compose::NODE_140707421421632[] PROGMEM = {
	{{0, 1, L1, KEY_7}, {0x204a}},
	{{1, 1, L1, KEY_8}, {0x215e}},
};

const Node Compose::NODE_140707421421872[] PROGMEM = {
	{{0, 0, L1, KEY_1}, {(uint16_t) NODE_140707421421792}},
	{{0, 1, L1, KEY_2}, {0x2161}},
	{{0, 1, L1, KEY_3}, {0x2162}},
	{{0, 1, L1, KEY_4}, {0x2163}},
	{{0, 1, L1, KEY_5}, {0x2164}},
	{{0, 1, L1, KEY_6}, {0x2165}},
	{{0, 1, L1, KEY_7}, {0x2166}},
	{{0, 1, L1, KEY_8}, {0x2167}},
	{{1, 1, L1, KEY_9}, {0x2168}},
};

const Node Compose::NODE_140707421421792[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x2160}},
	{{0, 1, L1, KEY_0}, {0x2169}},
	{{0, 1, L1, KEY_1}, {0x216a}},
	{{1, 1, L1, KEY_2}, {0x216b}},
};

const Node Compose::NODE_140707421422832[] PROGMEM = {
	{{0, 0, L1, KEY_1}, {(uint16_t) NODE_140707421422992}},
	{{0, 1, L1, KEY_2}, {0x2171}},
	{{0, 1, L1, KEY_3}, {0x2172}},
	{{0, 1, L1, KEY_4}, {0x2173}},
	{{0, 1, L1, KEY_5}, {0x2174}},
	{{0, 1, L1, KEY_6}, {0x2175}},
	{{0, 1, L1, KEY_7}, {0x2176}},
	{{0, 1, L1, KEY_8}, {0x2177}},
	{{1, 1, L1, KEY_9}, {0x2178}},
};

const Node Compose::NODE_140707421422992[] PROGMEM = {
	{{0, 1, L1, KEY_SPACE}, {0x2170}},
	{{0, 1, L1, KEY_0}, {0x2179}},
	{{0, 1, L1, KEY_1}, {0x217a}},
	{{1, 1, L1, KEY_2}, {0x217b}},
};

const Node Compose::NODE_140707421424272[] PROGMEM = {
	{{0, 1, L1, KEY_5}, {0x2157}},
	{{0, 1, L1, KEY_8}, {0x215c}},
	{{1, 1, L1, KEY_4}, {0xbe}},
};

const Node Compose::NODE_140707421424352[] PROGMEM = {
	{{1, 1, L1, KEY_5}, {0x2158}},
};

const Node Compose::NODE_140707421424672[] PROGMEM = {
	{{0, 1, L1, KEY_6}, {0x215a}},
	{{1, 1, L1, KEY_8}, {0x215d}},
};

const Node Compose::NODE_140707421446368[] PROGMEM = {
	{{0, 1, L3, KEY_K}, {0x263a}},
	{{1, 1, L3, KEY_J}, {0x2639}},
};

const Node Compose::NODE_140707421446608[] PROGMEM = {
	{{1, 0, L3, KEY_S}, {(uint16_t) NODE_140707421446768}},
};

const Node Compose::NODE_140707421446768[] PROGMEM = {
	{{1, 1, L1, KEY_G}, {0x2105}},
};

const Node Compose::NODE_140707421446688[] PROGMEM = {
	{{0, 1, L5, KEY_5}, {0x26a2}},
	{{1, 1, L5, KEY_4}, {0x26a4}},
};

const Node Compose::NODE_140707421446928[] PROGMEM = {
	{{0, 1, L5, KEY_4}, {0x26a3}},
	{{1, 1, L5, KEY_5}, {0x26a4}},
};

const Node Compose::NODE_140707421448048[] PROGMEM = {
	{{1, 1, L1, KEY_3}, {0x2665}},
};

const Node Compose::NODE_140707421448368[] PROGMEM = {
	{{1, 0, L2, KEY_J}, {(uint16_t) NODE_140707421448448}},
};

const Node Compose::NODE_140707421448448[] PROGMEM = {
	{{1, 1, L2, KEY_SEMICOLON}, {0x262e}},
};

const Node Compose::NODE_140707421448208[] PROGMEM = {
	{{1, 1, L3, KEY_R}, {0x25a1}},
};

const Node Compose::NODE_140707421448608[] PROGMEM = {
	{{0, 1, L2, KEYPAD_7}, {0x2611}},
	{{1, 1, L2, KEYPAD_8}, {0x2612}},
};

const Node Compose::NODE_140707421448768[] PROGMEM = {
	{{1, 1, L6, KEYPAD_0}, {0x2611}},
};

const Node Compose::NODE_140707421449088[] PROGMEM = {
	{{1, 1, L6, KEYPAD_0}, {0x2612}},
};

const Node Compose::NODE_140707421449168[] PROGMEM = {
	{{1, 1, L3, KEY_Y}, {0x26a0}},
};

const Node Compose::NODE_140707421449568[] PROGMEM = {
	{{1, 1, L2, KEYPAD_0}, {0x237d}},
};

const Node Compose::NODE_140707421449648[] PROGMEM = {
	{{0, 1, L1, KEY_O}, {0x20b0}},
	{{1, 0, L1, KEY_G}, {(uint16_t) NODE_140707421450048}},
};

const Node Compose::NODE_140707421450048[] PROGMEM = {
	{{1, 1, L1, KEY_S}, {0x2318}},
};

const Node Compose::NODE_140707421463072[] PROGMEM = {
	{{1, 0, L3, KEY_S}, {(uint16_t) NODE_140707421463152}},
};

const Node Compose::NODE_140707421463152[] PROGMEM = {
	{{1, 1, L1, KEY_PERIOD}, {0x2052}},
};

const Node Compose::NODE_140707421463312[] PROGMEM = {
	{{1, 1, L2, KEY_PERIOD}, {0x2023}},
};


/*
 * Mapping of Keys which exist multiple times on keyboard
 * left Sequence will be remapped right sequence for lookup
*/
const LayeredKey Compose::aliases[][2] {
	{{L3, KEY_L}, {L1, KEY_MINUS}},
	{{L1, KEYPAD_SUBTRACT}, {L1, KEY_MINUS}},
	{{L1, KEYPAD_1}, {L1, KEY_1}},
	{{L1, KEYPAD_2}, {L1, KEY_2}},
	{{L1, KEYPAD_3}, {L1, KEY_3}},
	{{L1, KEYPAD_4}, {L1, KEY_4}},
	{{L1, KEYPAD_5}, {L1, KEY_5}},
	{{L1, KEYPAD_6}, {L1, KEY_6}},
	{{L1, KEYPAD_7}, {L1, KEY_7}},
	{{L1, KEYPAD_8}, {L1, KEY_8}},
	{{L1, KEYPAD_9}, {L1, KEY_9}},
	{{L1, KEYPAD_0}, {L1, KEY_0}},
	{{L1, KEYPAD_DIVIDE}, {L3, KEY_S}},
	{{L1, KEYPAD_MULTIPLY}, {L3, KEY_G}},
	{{L1, KEYPAD_ADD}, {L3, KEY_N}},
	{{L3, KEY_NUM_LOCK}, {L3, KEY_O}},
};

LayeredKey Compose::getAlias(uint8_t layer, uint8_t key) {
	for(int16_t i = 0; i < (sizeof(aliases) / sizeof(aliases[0])); i++){
		if(layer == aliases[i][0].layer && key == aliases[i][0].key){
			return aliases[i][1];
		}
	}
	return {0,0};
}

uint16_t Compose::transition(uint8_t layer, uint8_t key) {
	Node* cur = currentNode;
	Node val_cur;
	
	LayeredKey alias = getAlias(layer, key);
	if(alias.layer != 0 && alias.key != 0){
		layer = alias.layer;
		key = alias.key;
	}
	
	do {
		memcpy_P(&val_cur, cur, sizeof(val_cur));
		if (val_cur.layeredKey.layer == layer && val_cur.layeredKey.keycode == key) { //found
			if (val_cur.layeredKey.isLeaf) {
				currentNode = const_cast<Node*>(root);
				return val_cur.payload.unicode;
				
			} else { //found, waiting for next key
				currentNode = const_cast<Node*>(val_cur.payload.nodes);
				return 1;
			}
		}
		cur++;
	} while (val_cur.layeredKey.isLastElement == 0);
	
	//not found
	currentNode = const_cast<Node*>(root);
	return 0;
}

void Compose::reset(){
	currentNode = const_cast<Node*>(root);
}